/**
 * アプリケーションのエラーコード定義
 */
export enum ErrorCode {
  // 一般的なエラー
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INVALID_INPUT = "INVALID_INPUT",
  UNAUTHORIZED = "UNAUTHORIZED",

  // バトルセッション関連
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_CREATE_FAILED = "SESSION_CREATE_FAILED",
  SESSION_UPDATE_FAILED = "SESSION_UPDATE_FAILED",
  SESSION_DELETE_FAILED = "SESSION_DELETE_FAILED",
  SESSION_LIMIT_EXCEEDED = "SESSION_LIMIT_EXCEEDED",
  SESSION_TITLE_TOO_LONG = "SESSION_TITLE_TOO_LONG",

  // メモ関連
  MEMO_NOT_FOUND = "MEMO_NOT_FOUND",
  MEMO_CREATE_FAILED = "MEMO_CREATE_FAILED",
  MEMO_UPDATE_FAILED = "MEMO_UPDATE_FAILED",
  MEMO_DELETE_FAILED = "MEMO_DELETE_FAILED",

  // ストレージ関連
  STORAGE_READ_ERROR = "STORAGE_READ_ERROR",
  STORAGE_WRITE_ERROR = "STORAGE_WRITE_ERROR",
}

/**
 * エラーの重大度
 */
export enum ErrorSeverity {
  INFO = "INFO",
  WARNING = "WARNING",
  ERROR = "ERROR",
  CRITICAL = "CRITICAL",
}

/**
 * エラーコンテキスト情報の型定義
 */
export interface ErrorContext {
  [key: string]: unknown;
}
